global:
  scrape_interval: 5s
  external_labels:
    monitor: "prometheus_monitor"

rule_files:
  # write rules later

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  #  Scrape application endpoint protected
  # - job_name: api
  #   static_configs:
  #     - targets: ["192.168.1.3:8080"]
  #   basic_auth:
  #     username: 'admin'
  #     password: 'password'